### ISSUE TITLE
无法编译通过

### ISSUE THREAD

**Issue by goldtimes** [Yixin-F/better_fastlio2#2]
common_lib.h中缺少了Pose6D save_map等等的头文件

**Comment by goldtimes** [comment]
我的问题，已经解决

**Comment by keepermzw** [comment]
你好，请问是怎么解决的呢？

**Comment by Yixin-F** [comment]
应该是cmakelist.txt里边编译顺序问题，许多开源项目都有类似问题，可以重复编译几次，应该可以解决

**Comment by zxhasd** [comment]
同问，该怎么解决呢，重复编译没有效果

**Comment by zxhasd** [comment]
解决了，把make默认的-j4 -l4换成-j8 -l8编译通过了
